### ISSUE TITLE
想问一下您，在微信浏览器中用safari打开是怎么实现打开商品详情页面的？

### ISSUE THREAD

**Issue by inmWang** [jdfdcc/vue-mobile-mint#2]
这个问题纠结了很久，到现在还没实现，只好给您提个issues，希望能给个答复～

**Comment by zoro-r** [comment]
抱歉啊，这个问题也一直在困扰着我，微信不会记录路由的变化，开启history模式不知道能不能实现，希望能够帮到你，谢谢提问！！！
